routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('call-groups', 'CallGroupsController');
Route::resource('call-list', 'CallListsController');

app/CallGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\CallList;

class CallGroup extends Model
{
    //

    public function call_lists()
    {
        return $this->hasMany(CallList::class);
    }
}

app/CallList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\CallGroup;

class CallList extends Model
{
    protected $fillable = ['level'];
    //
    // public function call_group()
    // {
    //     return $this->belongsTo(CallGroup::class);
    // }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CallGroupsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\CallGroup;
use App\CallList;

class CallGroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('callgroups.index')->with('callgroups', CallGroup::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CallListsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CallList;

class CallListsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('calllists.index')->with(
            'calllists',
            CallList::orderBy('level', 'asc')->get()
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $button = array_keys($request->all());
        $button_pressed = end($button);
        $calllistToSwitch = CallList::find($id);
        $allCallList = CallList::all();
        $previous_level = $calllistToSwitch->level;

        switch ($button_pressed) {
            case "top":
                foreach ($allCallList as $calllist) {
                    if ($calllist->level < $calllistToSwitch->level) {
                        $calllist->update([
                            'level' => $calllist->level + 1
                        ]);
                    }
                }

                $calllistToSwitch->update([
                    'level' => 1
                ]);
                break;
            case "bottom":
                foreach ($allCallList as $calllist) {
                    if ($calllist->level > $calllistToSwitch->level) {
                        $calllist->update([
                            'level' => $calllist->level - 1
                        ]);
                    }
                }

                $calllistToSwitch->update([
                    'level' => count($allCallList)
                ]);
                break;

            case "up":
                foreach ($allCallList as $calllist) {
                    if ($calllist->level == $previous_level - 1) {
                        $calllist->update([
                            'level' => $calllist->level + 1
                        ]);
                        break;
                    }
                }

                $calllistToSwitch->update([
                    'level' => $previous_level - 1
                ]);

                break;
            case "down":
                foreach ($allCallList as $calllist) {
                    if ($calllist->level == $previous_level + 1) {
                        $calllist->update([
                            'level' => $calllist->level - 1
                        ]);
                        break;
                    }
                }

                $calllistToSwitch->update([
                    'level' => $previous_level + 1
                ]);

                break;
            default:
                return;
        }

        return redirect(route('call-list.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/callgroups/index.blade.php
@extends('layouts.app')

@section('content')    
    <table class="table">
        <thead>
            <th>Group Name</th>
            <th></th>
        </thead>
        <tbody>
            @foreach ($callgroups as $callgroup)    
                <tr>
                    <td>
                        <a href="/call-list">
                            {{$callgroup->name}}
                        </a>
                    </td>
                    <td>
                        {{$callgroup->call_group_id}}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/calllists/index.blade.php
@extends('layouts.app')

@section('content')
    <table class="table">
        <thead> 
            <th>Level</th>
            <th>Name</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach ($calllists as $calllist)    
                <tr>
                    <td>{{ $calllist->level }}</td>
                    <td>{{ $calllist->name }}</td>
                    <td>
                        
                        <form action="{{ route('call-list.update', $calllist->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <button name="top" type="submit" class="btn btn-primary">Top</button>
                            <button name="up" class="btn btn-primary">Up</button>
                            <button name="down" class="btn btn-primary">Down</button>
                            <button name="bottom" class="btn btn-primary">Bottom</button>
                        </form>
                        
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    @yield('content')

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>